### PR TITLE
Maxb/merge fix

### PR DESCRIPTION
**Pull request by max-b**
@Juul - I believe this should be our current up to date master branch. Want to take a quick look and let me know if it's ok to merge this to master?

Also - I'm not 100% convinced by the change you made here: https://github.com/sudomesh/tunneldigger/blob/master/client/l2tp_client.c#L332

I don't think that should have the `strlen(force_iface) + 1` parameter. My understanding is that it should be the size of the `force_iface` parameter, which I think in this case translates to just `strlen(force_iface)`. Am I missing something here?

### CODE REVIEW

**Comment by Juul** [comment]
hm ok i can have a look, but yes I am sure about that change. The setsockopt call is expecting a null terminated string and strlen gives the string excluding the null terminator. Without that change the code only works of the next byte in memory after where the string is allocated happens to be all zeroes.

**Comment by max-b** [comment]
> The setsockopt call is expecting a null terminated string and strlen gives the string excluding the null terminator

Why don't we just null terminate the string then?

**Comment by max-b** [comment]
Also - I'm becoming less certain about this merge situation. If it were completely up to me I think I'd actually re-write history and do a hard reset back to 72c6e4c6f0d8c8d05b0f1d074d6cd237201f28b9, then implement your setsockopt fix and then do the upstream merging. The problem is that I can't seem to find a way to make that happen without re-writing history. `git revert`, especially when reverting merges, is a very peculiar animal, and I'm not totally certain that I can make it do what I want in this case.

**Comment by max-b** [comment]
Ok I think I fixed this by re-writing some more history. Likely everyone will need to do a fresh clone, but so goes it.

**Pull request closed without merging**
